In [1]:
import pandas as pd

In [2]:
data =  pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0

In [4]:
dataset = data[['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']]

In [5]:
dataset

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [6]:
geo = pd.get_dummies(dataset['Geography'], drop_first=True)

In [7]:
geo.columns

Index(['Germany', 'Spain'], dtype='object')

In [8]:
x = dataset.iloc[ : , [0,3,4,5,6,7,8]]

In [9]:
x

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember
0,619,42,2,0.00,1,1,1
1,608,41,1,83807.86,1,0,1
2,502,42,8,159660.80,3,1,0
3,699,39,1,0.00,2,0,0
4,850,43,2,125510.82,1,1,1
...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0
9996,516,35,10,57369.61,1,1,1
9997,709,36,7,0.00,1,0,1
9998,772,42,3,75075.31,2,1,0
9999,792,28,4,130142.79,1,1,0

In [10]:
x = x.iloc[:, 0:9]

In [11]:
x[['Germany', 'Spain']] = geo

In [12]:
x

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Germany,Spain
0,619,42,2,0.00,1,1,1,0,0
1,608,41,1,83807.86,1,0,1,0,1
2,502,42,8,159660.80,3,1,0,0,0
3,699,39,1,0.00,2,0,0,0,0
4,850,43,2,125510.82,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,0,0
9996,516,35,10,57369.61,1,1,1,0,0
9997,709,36,7,0.00,1,0,1,0,0
9998,772,42,3,75075.31,2,1,0,1,0
9999,792,28,4,130142.79,1,1,0,0,0

In [13]:
gender = pd.get_dummies(dataset['Gender'], drop_first=True)

In [14]:
gender

      Male
0        0
1        0
2        0
3        0
4        0
...    ...
9995     1
9996     1
9997     0
9998     1
9999     0

[10000 rows x 1 columns]

In [15]:
x = x.iloc[: , 0:10]

In [16]:
x[['gender']] = gender

In [17]:
x

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Germany,Spain,gender
0,619,42,2,0.00,1,1,1,0,0,0
1,608,41,1,83807.86,1,0,1,0,1,0
2,502,42,8,159660.80,3,1,0,0,0,0
3,699,39,1,0.00,2,0,0,0,0,0
4,850,43,2,125510.82,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,0,0,1
9997,709,36,7,0.00,1,0,1,0,0,0
9998,772,42,3,75075.31,2,1,0,1,0,1
9999,792,28,4,130142.79,1,1,0,0,0,0

In [18]:
y = dataset['EstimatedSalary']

In [19]:
y

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [20]:
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [21]:
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.15, random_state=42)

In [22]:
model = LinearRegression()

In [23]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
y_pred = model.predict(X_test)

In [30]:
y_test.shape

(1500,)

In [29]:
y_pred.shape

(1500,)

In [27]:
error = mean_squared_error(y_test, y_pred)

In [28]:
error

3315381988.2444882

In [32]:
x

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Germany,Spain,gender
0,619,42,2,0.00,1,1,1,0,0,0
1,608,41,1,83807.86,1,0,1,0,1,0
2,502,42,8,159660.80,3,1,0,0,0,0
3,699,39,1,0.00,2,0,0,0,0,0
4,850,43,2,125510.82,1,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,0,0,1
9997,709,36,7,0.00,1,0,1,0,0,0
9998,772,42,3,75075.31,2,1,0,1,0,1
9999,792,28,4,130142.79,1,1,0,0,0,0

In [44]:
from sklearn.linear_model import Lasso

In [45]:
from sklearn.feature_selection import SelectFromModel

In [46]:
sel = SelectFromModel(Lasso(alpha=0.01))

In [47]:
sel.fit(X_train, y_train)

SelectFromModel(estimator=Lasso(alpha=0.01, copy_X=True, fit_intercept=True,
                                max_iter=1000, normalize=False, positive=False,
                                precompute=False, random_state=None,
                                selection='cyclic', tol=0.0001,
                                warm_start=False),
                max_features=None, norm_order=1, prefit=False, threshold=None)

In [48]:
sel.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [49]:
sel.estimator_.coef_

array([-3.60997355e+00, -2.01080631e+01,  2.65720577e+02,  1.52402507e-02,
        1.80763269e+03, -1.59636618e+03, -1.22496713e+03,  1.29720259e+02,
       -4.91720340e+02, -1.37653029e+03])

In [50]:
model = LinearRegression()

In [51]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [52]:
y_predict = model.predict(X_test)

In [53]:
y_predict

array([102641.44014574,  97366.29021444, 100332.58020294, ...,
       100345.3495358 ,  99678.48633043,  99803.90487294])

In [54]:
y_test

6252     41788.37
4684    146379.30
1731     58561.31
4742    170679.74
4521    114669.79
          ...
967      26057.08
6043     93881.75
6879    112256.57
6775    160529.71
3295    189641.11
Name: EstimatedSalary, Length: 1500, dtype: float64