In [13]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston

from sklearn.linear_model import LinearRegression
from  sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [14]:
data =  load_boston()

In [15]:
print(data.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**

    :Number of Instances: 506

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
        - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
        - LSTAT    % lower status of the population
        - MEDV     Median value of owner-occupied homes in $1000's

    :Missing Attribute Values: None

    :Creator: Harrison, D. and Rubinfeld, D.L.

This is a copy of UCI ML housing dataset.
https://archive.ics.uci.edu/ml/machine-learning-databases/housing/


This dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.

The Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic
prices and the demand for clean air', J. Environ. Economics & Management,
vol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics
...', Wiley, 1980.   N.B. Various transformations are used in the table on
pages 244-261 of the latter.

The Boston house-price data has been used in many machine learning papers that address regression
problems.

.. topic:: References

   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.
   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.

In [16]:
dataset = pd.DataFrame(data.data, columns = data.feature_names)

In [17]:
target = pd.DataFrame(data.target, columns=['target'])

In [18]:
target

     target
0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
..      ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9

[506 rows x 1 columns]

In [19]:
dataset.corr

<bound method DataFrame.corr of         CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0

     PTRATIO       B  LSTAT
0       15.3  396.90   4.98
1       17.8  396.90   9.14
2       17.8  392.83   4.03
3       18.7  394.63   2.94
4       18.7  396.90   5.33
..       ...     ...    ...
501     21.0  391.99   9.67
502     21.0  396.90   9.08
503     21.0  396.90   5.64
504     21.0  393.45   6.48
505     21.0  396.90   7.88

[506 rows x 13 columns]>

In [20]:
 X_train, X_test, y_train, y_test = train_test_split( dataset, target, test_size=0.15, random_state=42)

In [22]:
model = LinearRegression()

In [23]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [26]:
y_pred = model.predict(X_test)

In [27]:
y_pred

array([[29.4299146 ],
       [36.12913024],
       [14.29515659],
       [24.85869473],
       [18.9459364 ],
       [23.33181044],
       [17.56304359],
       [13.64580456],
       [23.76767942],
       [20.67064862],
       [24.97566126],
       [18.64115832],
       [-5.37529568],
       [21.53577018],
       [19.55628157],
       [26.20738657],
       [20.71765252],
       [ 6.43165738],
       [40.54410761],
       [17.84455626],
       [27.23309618],
       [30.3543635 ],
       [11.18673244],
       [23.7090171 ],
       [18.4391652 ],
       [16.89075459],
       [22.82856829],
       [14.88561852],
       [22.4084684 ],
       [19.26626721],
       [23.20312101],
       [25.09863053],
       [25.77705635],
       [18.73128221],
       [17.35488263],
       [16.92397997],
       [30.81465816],
       [20.11645382],
       [23.47005166],
       [24.25945046],
       [13.99527168],
       [32.81595458],
       [42.84191019],
       [17.36577587],
       [27.36376775],
       [17.65205456],
       [14.17099713],
       [25.45190626],
       [20.76675071],
       [30.06772594],
       [21.45925197],
       [34.42220955],
       [15.74704153],
       [25.99425554],
       [39.49038628],
       [22.82111596],
       [19.13064128],
       [33.1975165 ],
       [24.9068507 ],
       [13.02579225],
       [22.28159258],
       [30.44316337],
       [31.60763587],
       [16.03484901],
       [19.92414044],
       [16.88585295],
       [20.74312801],
       [26.06425151],
       [31.03448877],
       [12.3460523 ],
       [20.398064  ],
       [27.9487637 ],
       [11.35482353],
       [15.73858043],
       [23.76119167],
       [ 6.26520854]])

In [29]:
y_test

     target
173    23.6
274    32.4
491    13.6
72     22.8
452    16.1
..      ...
481    23.7
444    10.8
355    20.6
77     20.8
398     5.0

[76 rows x 1 columns]

In [30]:
error = mean_squared_error(y_test, y_pred)

In [31]:
error

13.718854722908782